version: '3.1'

services:

  node-server:
    # ตั้งชื่อ container (เหมือน --name)
    container_name: node-server
    command: node --watch ./dist/server
    build: . # ตำแหน่ง dockerfile
    restart: always
    ports:
      - "8080:8080" 

    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DBHOST=${DBHOST}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBNAME=${DBNAME}
      - DBPORT=${DBPORT}
      - JWT_SECRET=${JWT_SECRET}