version: '3.1'

services:

  node-server:
    # ตั้งชื่อ container (เหมือน --name)
    container_name: node-server
    command: node --watch ./dist/server
    build: . # ตำแหน่ง dockerfile
    restart: always
    ports:
      - "8080:8080" # map port ออกมา เหมือน -p ใน docker run
    env_file:
      - .env
    environment:
      - PORT = ${PORT}
      - DBHOST = ${DBHOST}
      - DBUSER = ${DBUSER}
      - DBPASS = ${DBPASS}
      - DBNAME = ${DBNAME}
      - DBPORT = ${DBPORT}
      - JWT_SECRET = ${JWT_SECRET}
